#!/usr/bin/env node
const engine = require("../src/engine");

function parse(argv) {
  const out = {};
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === "--repo" || arg === "--repository-root") {
      out.repositoryRoot = argv[i + 1];
      i += 1;
    } else if (arg === "--index-root") {
      out.indexRoot = argv[i + 1];
      i += 1;
    }
  }
  return out;
}

const args = parse(process.argv.slice(2));
const result = engine.validateIndex({
  repositoryRoot: args.repositoryRoot,
  indexRoot: args.indexRoot,
});
console.log(JSON.stringify(result, null, 2));
