#!/usr/bin/env node

const {
  parseArgs,
  loadConfig,
  loadMissionState,
  buildAllPages,
  writeText,
} = require("./_wiki-lib");

const args = parseArgs(process.argv.slice(2));
if (args.flags.help) {
  console.log("Usage: node generate-wiki-pages [--output-dir wiki]");
  process.exit(0);
}

const config = loadConfig();
if (args.flags["output-dir"]) {
  config.output_dir = args.flags["output-dir"];
}

const state = loadMissionState();
const outputs = buildAllPages(config, state);
for (const output of outputs) {
  writeText(output.path, output.content);
  console.log(`generated ${output.path}`);
}
